### ISSUE TITLE
About distractor-aware training implementation

### ISSUE THREAD

**Issue by lzw19951010** [MathsXDC/DaSiamRPNWithOfflineTraining#1]
Hi, MathsXDC:
Thank you for your great work! I've just read your implementation, and I'm having trouble finding the implementation of distractor-aware training part in your code. I briefly summarized my questions as below:

1. How do you sample negative pairs in your code?
2. Did you test your performance on the vot benchmark?

It would be great if you could enlighten me on above questions. Thank you very much!

**Comment by MathsXDC** [comment]
Thanks a million for your interest! The repo had not implemented the distractor-aware part when you read it. But now, it has been included into the testing module. There's no distractor-aware offline training according to my understanding of the related papers. As for your specific questions, the sampling strategy for selecting offline training pairs has not been implemented, nor has the evaluation of the testing module. These issues will be resolved in the future. For the latest improvement, you may read ReadMe again. ^_^

**Comment by MathsXDC** [comment]
@lzw19951010 Thanks a million for your interest. This implementation of distractor-aware part had not been completed when you read this repo. But now, it has been included into the testing module. According to my understanding of the relevant papers, there's no distractor-aware offline training. As for your specific questions, the sampling strategy for pairing has not been implemented, nor has the evaluation of the testing module on any benchmark. For latest improvement, you can refer to ReadMe once again. These issues you raised will be resolved later. ^_^
